### ISSUE TITLE
Size mismatch in SigmoidCrossEntropyLoss

### ISSUE THREAD

**Issue by jason718** [philkr/voc-classification#5]
I met this bug and have no idea why it happenes

Traceback (most recent call last):
  File "src/train_cls.py", line 121, in <module>
    s.run(args.nit)
  File "/home/jason/egomotion/experiment/voc2007_cls/voc-classification/src/solver.py", line 90, in run
    s.step(1)
  File "/home/jason/egomotion/experiment/voc2007_cls/voc-classification/src/python_layers.py", line 54, in forward
    lZ  = np.log(1+np.exp(-np.abs(f))) \* mask
ValueError: operands could not be broadcast together with shapes (10,20) (16,20)

**Comment by jason718** [comment]
Found the problem. the default bn is set to 16.

**Comment by jason718** [comment]
It seems like if I set batch size to some number rather than 10, this problem will happen.

**Comment by polo5** [comment]
@jason718 did you then get this error in the test phase:

```
File "src/train_cls.py", line 169, in <module>
    ap = metrics.average_precision_score(gts[i][gts[i]<=1], scr[i][gts[i]<=1]-1e-5*gts[i][gts[i]<=1])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 49520 but corresponding boolean dimension is 4952
```

My test_resize_layer.cpp failed in the 'make test' compiling so I removed it. I have a feeling this is what is causing all those shape mismatches now. Here the ground truths are shape (20, 4920) but the scores are (20, 49520)

**Comment by polo5** [comment]
@jason718 I just realized that contrary to Tensorflow the batch size is hardcoded in caffe, so we need to set the batch size equal to the one specified in whatever prototxt we are providing. 

For bvlc_reference_caffenet that is indeed 10. For Rotnet it's 4 etc.

**Comment by jason718** [comment]
@polo5 does the batch size matters in terms of final results?

**Comment by polo5** [comment]
To be honnest I haven't been able to get any reasonable mAP score yet so I can't say. I get a weird error (see #7 ) which when fixed gives me a 3% mAP.  I've tried the models: bvlc_reference_caffenet, alexnet, rotnet. Any luck on your side?

**Comment by jason718** [comment]
I used this long time ago, and I have published a paper: https://jason718.github.io/project/cvpr18/main.html

**Comment by jianghaojun** [comment]
It's a mismatch between batchsize( set by -bs ) and the first dimension in input layer (set in yournetwork.prototxt).
